<?php

use Illuminate\Database\Seeder;

class CurrencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currency')->truncate();
        DB::table('currency')->insert([
            ['currency_code' => 'ADP', 'currency_name' => 'Andorran Peseta'],
            ['currency_code' => 'AED', 'currency_name' => 'United Arab Emirates Dirham'],
            ['currency_code' => 'AFA', 'currency_name' => 'Afghanistan Afghani'],
            ['currency_code' => 'ALL', 'currency_name' => 'Albanian Lek'],
            ['currency_code' => 'ANG', 'currency_name' => 'Netherlands Antillian Guilder'],
            ['currency_code' => 'AOK', 'currency_name' => 'Angolan Kwanza'],
            ['currency_code' => 'ARS', 'currency_name' => 'Argentine Peso'],
            ['currency_code' => 'AUD', 'currency_name' => 'Australian Dollar'],
            ['currency_code' => 'AWG', 'currency_name' => 'Aruban Florin'],
            ['currency_code' => 'BBD', 'currency_name' => 'Barbados Dollar'],
            ['currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka'],
            ['currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev'],
            ['currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar'],
            ['currency_code' => 'BIF', 'currency_name' => 'Burundi Franc'],
            ['currency_code' => 'BMD', 'currency_name' => 'Bermudian Dollar'],
            ['currency_code' => 'BND', 'currency_name' => 'Brunei Dollar'],
            ['currency_code' => 'BOB', 'currency_name' => 'Bolivian Boliviano'],
            ['currency_code' => 'BRL', 'currency_name' => 'Brazilian Real'],
            ['currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar'],
            ['currency_code' => 'BTN', 'currency_name' => 'Bhutan Ngultrum'],
            ['currency_code' => 'BUK', 'currency_name' => 'Burma Kyat'],
            ['currency_code' => 'BWP', 'currency_name' => 'Botswanian Pula'],
            ['currency_code' => 'BZD', 'currency_name' => 'Belize Dollar'],
            ['currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar'],
            ['currency_code' => 'CHF', 'currency_name' => 'Swiss Franc'],
            ['currency_code' => 'CLF', 'currency_name' => 'Chilean Unidades de Fomento'],
            ['currency_code' => 'CLP', 'currency_name' => 'Chilean Peso'],
            ['currency_code' => 'CNY', 'currency_name' => 'Yuan (Chinese) Renminbi'],
            ['currency_code' => 'COP', 'currency_name' => 'Colombian Peso'],
            ['currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colon'],
            ['currency_code' => 'CZK', 'currency_name' => 'Czech Republic Koruna'],
            ['currency_code' => 'CUP', 'currency_name' => 'Cuban Peso'],
            ['currency_code' => 'CVE', 'currency_name' => 'Cape Verde Escudo'],
            ['currency_code' => 'CYP', 'currency_name' => 'Cyprus Pound'],
            ['currency_code' => 'DKK', 'currency_name' => 'Danish Krone'],
            ['currency_code' => 'DOP', 'currency_name' => 'Dominican Peso'],
            ['currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar'],
            ['currency_code' => 'ECS', 'currency_name' => 'Ecuador Sucre'],
            ['currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound'],
            ['currency_code' => 'EEK', 'currency_name' => 'Estonian Kroon (EEK)'],
            ['currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr'],
            ['currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['currency_code' => 'FJD', 'currency_name' => 'Fiji Dollar'],
            ['currency_code' => 'FKP', 'currency_name' => 'Falkland Islands Pound'],
            ['currency_code' => 'GBP', 'currency_name' => 'British Pound'],
            ['currency_code' => 'GHC', 'currency_name' => 'Ghanaian Cedi'],
            ['currency_code' => 'GIP', 'currency_name' => 'Gibraltar Pound'],
            ['currency_code' => 'GMD', 'currency_name' => 'Gambian Dalasi'],
            ['currency_code' => 'GNF', 'currency_name' => 'Guinea Franc'],
            ['currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal'],
            ['currency_code' => 'GWP', 'currency_name' => 'Guinea-Bissau Peso'],
            ['currency_code' => 'GYD', 'currency_name' => 'Guyanan Dollar'],
            ['currency_code' => 'HKD', 'currency_name' => 'Hong Kong Dollar'],
            ['currency_code' => 'HNL', 'currency_name' => 'Honduran Lempira'],
            ['currency_code' => 'HTG', 'currency_name' => 'Haitian Gourde'],
            ['currency_code' => 'HUF', 'currency_name' => 'Hungarian Forint'],
            ['currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah'],
            ['currency_code' => 'IEP', 'currency_name' => 'Irish Punt'],
            ['currency_code' => 'ILS', 'currency_name' => 'Israeli Shekel'],
            ['currency_code' => 'INR', 'currency_name' => 'Indian Rupee'],
            ['currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar'],
            ['currency_code' => 'IRR', 'currency_name' => 'Iranian Rial'],
            ['currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar'],
            ['currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar'],
            ['currency_code' => 'JPY', 'currency_name' => 'Japanese Yen'],
            ['currency_code' => 'KES', 'currency_name' => 'Kenyan Schilling'],
            ['currency_code' => 'KHR', 'currency_name' => 'Kampuchean (Cambodian) Riel'],
            ['currency_code' => 'KMF', 'currency_name' => 'Comoros Franc'],
            ['currency_code' => 'KPW', 'currency_name' => 'North Korean Won'],
            ['currency_code' => 'KRW', 'currency_name' => '(South) Korean Won'],
            ['currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar'],
            ['currency_code' => 'KYD', 'currency_name' => 'Cayman Islands Dollar'],
            ['currency_code' => 'LAK', 'currency_name' => 'Lao Kip'],
            ['currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound'],
            ['currency_code' => 'LKR', 'currency_name' => 'Sri Lanka Rupee'],
            ['currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar'],
            ['currency_code' => 'LSL', 'currency_name' => 'Lesotho Loti'],
            ['currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar'],
            ['currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham'],
            ['currency_code' => 'MGF', 'currency_name' => 'Malagasy Franc'],
            ['currency_code' => 'MNT', 'currency_name' => 'Mongolian Tugrik'],
            ['currency_code' => 'MOP', 'currency_name' => 'Macau Pataca'],
            ['currency_code' => 'MRO', 'currency_name' => 'Mauritanian Ouguiya'],
            ['currency_code' => 'MTL', 'currency_name' => 'Maltese Lira'],
            ['currency_code' => 'MUR', 'currency_name' => 'Mauritius Rupee'],
            ['currency_code' => 'MVR', 'currency_name' => 'Maldive Rufiyaa'],
            ['currency_code' => 'MWK', 'currency_name' => 'Malawi Kwacha'],
            ['currency_code' => 'MXP', 'currency_name' => 'Mexican Peso'],
            ['currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit'],
            ['currency_code' => 'MZM', 'currency_name' => 'Mozambique Metical'],
            ['currency_code' => 'NAD', 'currency_name' => 'Namibian Dollar'],
            ['currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira'],
            ['currency_code' => 'NIO', 'currency_name' => 'Nicaraguan Cordoba'],
            ['currency_code' => 'NOK', 'currency_name' => 'Norwegian Kroner'],
            ['currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee'],
            ['currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar'],
            ['currency_code' => 'OMR', 'currency_name' => 'Omani Rial'],
            ['currency_code' => 'PAB', 'currency_name' => 'Panamanian Balboa'],
            ['currency_code' => 'PEN', 'currency_name' => 'Peruvian Nuevo Sol'],
            ['currency_code' => 'PGK', 'currency_name' => 'Papua New Guinea Kina'],
            ['currency_code' => 'PHP', 'currency_name' => 'Philippine Peso'],
            ['currency_code' => 'PKR', 'currency_name' => 'Pakistan Rupee'],
            ['currency_code' => 'PLN', 'currency_name' => 'Polish Zloty'],
            ['currency_code' => 'PYG', 'currency_name' => 'Paraguay Guarani'],
            ['currency_code' => 'QAR', 'currency_name' => 'Qatari Rial'],
            ['currency_code' => 'RON', 'currency_name' => 'Romanian Leu'],
            ['currency_code' => 'RWF', 'currency_name' => 'Rwanda Franc'],
            ['currency_code' => 'SAR', 'currency_name' => 'Saudi Arabian Riyal'],
            ['currency_code' => 'SBD', 'currency_name' => 'Solomon Islands Dollar'],
            ['currency_code' => 'SCR', 'currency_name' => 'Seychelles Rupee'],
            ['currency_code' => 'SDP', 'currency_name' => 'Sudanese Pound'],
            ['currency_code' => 'SEK', 'currency_name' => 'Swedish Krona'],
            ['currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar'],
            ['currency_code' => 'SHP', 'currency_name' => 'St. Helena Pound'],
            ['currency_code' => 'SLL', 'currency_name' => 'Sierra Leone Leone'],
            ['currency_code' => 'SOS', 'currency_name' => 'Somali Schilling'],
            ['currency_code' => 'SRG', 'currency_name' => 'Suriname Guilder'],
            ['currency_code' => 'STD', 'currency_name' => 'Sao Tome and Principe Dobra'],
            ['currency_code' => 'RUB', 'currency_name' => 'Russian Ruble'],
            ['currency_code' => 'SVC', 'currency_name' => 'El Salvador Colon'],
            ['currency_code' => 'SYP', 'currency_name' => 'Syrian Potmd'],
            ['currency_code' => 'SZL', 'currency_name' => 'Swaziland Lilangeni'],
            ['currency_code' => 'THB', 'currency_name' => 'Thai Baht'],
            ['currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar'],
            ['currency_code' => 'TOP', 'currency_name' => 'Tongan Paanga'],
            ['currency_code' => 'TPE', 'currency_name' => 'East Timor Escudo'],
            ['currency_code' => 'TRY', 'currency_name' => 'Turkish Lira'],
            ['currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar'],
            ['currency_code' => 'TWD', 'currency_name' => 'Taiwan Dollar'],
            ['currency_code' => 'TZS', 'currency_name' => 'Tanzanian Schilling'],
            ['currency_code' => 'UGX', 'currency_name' => 'Uganda Shilling'],
            ['currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['currency_code' => 'UYU', 'currency_name' => 'Uruguayan Peso'],
            ['currency_code' => 'VEF', 'currency_name' => 'Venezualan Bolivar'],
            ['currency_code' => 'VND', 'currency_name' => 'Vietnamese Dong'],
            ['currency_code' => 'VUV', 'currency_name' => 'Vanuatu Vatu'],
            ['currency_code' => 'WST', 'currency_name' => 'Samoan Tala'],
            ['currency_code' => 'XAF', 'currency_name' => 'CommunautÃ© FinanciÃ¨re Africaine BEAC, Francs'],
            ['currency_code' => 'XAG', 'currency_name' => 'Silver, Ounces'],
            ['currency_code' => 'XAU', 'currency_name' => 'Gold, Ounces'],
            ['currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar'],
            ['currency_code' => 'XDR', 'currency_name' => 'International Monetary Fund (IMF) Special Drawing Rights'],
            ['currency_code' => 'XOF', 'currency_name' => 'CommunautÃ© FinanciÃ¨re Africaine BCEAO - Francs'],
            ['currency_code' => 'XPD', 'currency_name' => 'Palladium Ounces'],
            ['currency_code' => 'XPF', 'currency_name' => 'Comptoirs FranÃ§ais du Pacifique Francs'],
            ['currency_code' => 'XPT', 'currency_name' => 'Platinum, Ounces'],
            ['currency_code' => 'YDD', 'currency_name' => 'Democratic Yemeni Dinar'],
            ['currency_code' => 'YER', 'currency_name' => 'Yemeni Rial'],
            ['currency_code' => 'YUD', 'currency_name' => 'New Yugoslavia Dinar'],
            ['currency_code' => 'ZAR', 'currency_name' => 'South African Rand'],
            ['currency_code' => 'ZMK', 'currency_name' => 'Zambian Kwacha'],
            ['currency_code' => 'ZRZ', 'currency_name' => 'Zaire Zaire'],
            ['currency_code' => 'ZWD', 'currency_name' => 'Zimbabwe Dollar'],
            ['currency_code' => 'SKK', 'currency_name' => 'Slovak Koruna'],
            ['currency_code' => 'AMD', 'currency_name' => 'Armenian Dram']]);
    }
}
